### ISSUE TITLE
Create Best Practices Document for testing

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-summit-notes#9]
Basically write up how to write good tests and how the tests work:
- [ ] types of testing and their effectiveness
- [ ] testing platforms (start with linux, slowly add bsd, etc some like AIX will likely never be a thing
- [ ] testing tools: `travis`, `test-kitchen`, `kitchen-docker`,`(server|in)pec`, `rake`, etc

**Comment by mbbroberg** [comment]
Migrating to Community repo for ease of discoverability.
